apiVersion: v1
kind: Service
metadata:
  name: fastapi-ml
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fastapi-ml
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
